### ISSUE TITLE
bin/deploy -- UNREACHABLE

### ISSUE THREAD

**Issue by mazz** [danschultzer/ansible-phoenix-build#4]
I have port 22 opened on maz.me, and have my public key found locally in ~/.ssh/id_rsa.pub also in the /home/maz/.ssh/authorized_keys file on maz.me. I have confirmed that I can connect on port 22

I edited the bin/deploy where I append `-u maz` to the ansible-playbook call:

`ansible-playbook -i apps/production/inventory apps/production/deploy.yml -vvv -u maz`

I also tried setting `{{ ansible_user }}` to `maz`
and adding `ansible_user: maz` to the `maz.me`, `inventory` files

After all these changes I still get the error below when I run `bin/deploy` .. do you what I am missing?

```sh
fatal: [maz.me]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1514429373.232328-174544729471745 `\" && echo ansible-tmp-1514429373.232328-174544729471745=\"` echo ~/.ansible/tmp/ansible-tmp-1514429373.232328-174544729471745 `\" ), exited with result 1",
    "unreachable": true
}
```

**Comment by danschultzer** [comment]
Try change the user here: https://github.com/danschultzer/ansible-phoenix-build/blob/master/.ansible/apps/production/deploy.yml#L3

You won't need to change it any other place for deployment. I think I'll change it so it's set in inventory instead, it makes more sense.

**Comment by mazz** [comment]
Thanks for the quick reply.

in `deploy.yml` under `vars:`

```
  vars:
    local_release_dir: "{{ local_build_dir }}/_build/prod/rel/ansible_phoenix_build"
    build_version: "{{ lookup('file', local_build_dir + '/_build/prod/rel/ansible_phoenix_build/BUILD_VERSION') }}"
    commit_hash: "{{ lookup('file', local_build_dir + '/_build/prod/rel/ansible_phoenix_build/COMMIT_HASH') }}"
    ansible_user: "maz"
```
Also tried `ansible_user: maz` (no double-quotes). Both no change.


I even put literally `"maz"` and `maz` under `roles:` like:
```
  roles:
    - role: deploy_app/0.0.1
      app_name: ansible_phoenix_build
      username: maz 
```
and that did not seem to help .. not sure what's going on.

**Comment by danschultzer** [comment]
Do it above, after `hosts: all`, so it looks like this:

```yaml
---
- hosts: all
  user: maz
  gather_facts: no
```

**Comment by mazz** [comment]
after that, same issue, but I increased the verbosity of the errors to `-vvvv` and I saw:

```sh
fatal: [maz.me]: UNREACHABLE! => {
    "changed": false,
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1514434628.23786-108164615098615 `\" && echo ansible-tmp-1514434628.23786-108164615098615=\"` echo ~/.ansible/tmp/ansible-tmp-1514434628.23786-108164615098615 `\" ), exited with result 1, stderr output: Error: No such container: ansible_phoenix_build_build_server\n",
    "unreachable": true
}
```
the `stderr output: Error: No such container: ansible_phoenix_build_build_server\n` appears interesting ..

**Comment by danschultzer** [comment]
Ah, I know what's wrong. What's in your inventory? You probably have `ansible_connection` and `ansible_host` set to the docker container.

It should look like this:

```yaml
---
all:
  hosts:
    maz.me
  vars:
    local_build_dir: /tmp/my_app
```

**Comment by mazz** [comment]
yes it looks like this:
```sh
---
all:
  hosts:
    maz.me
  vars:
    ansible_connection: docker
    ansible_host: ansible_phoenix_build_build_server
    local_build_dir: /tmp/ansible_phoenix_build
    ansible_user: maz
```

**Comment by danschultzer** [comment]
I see, you probably figured it out already, but if you just change it to this, it should work:

```yaml
---
all:
  hosts:
    maz.me
  vars:
    local_build_dir: /tmp/ansible_phoenix_build
```
